const infrastructureData = [
  {
    id: 1,
    name: "Nairobi Expressway",
    county: "Nairobi",
    type: "Highway",
    status: "Completed",
    latitude: -1.3192,
    longitude: 36.8172,
    description: "Major road infrastructure project serving Nairobi.",
  },
  {
    id: 2,
    name: "Nakuru Road Project",
    county: "Nakuru",
    type: "Road",
    status: "Ongoing",
    latitude: -0.3031,
    longitude: 36.0800,
    description: "Road infrastructure project within Nakuru County.",
  },
  {
    id: 3,
    name: "Kisumu Infrastructure Project",
    county: "Kisumu",
    type: "Road",
    status: "Ongoing",
    latitude: -0.0917,
    longitude: 34.7680,
    description: "Transport infrastructure project serving Kisumu.",
  },
  {
    id: 4,
    name: "Mombasa Bridge Project",
    county: "Mombasa",
    type: "Bridge",
    status: "Planned",
    latitude: -4.0435,
    longitude: 39.6682,
    description: "Proposed bridge infrastructure project in Mombasa.",
  },
  {
    id: 5,
    name: "Nairobi Urban Road Project",
    county: "Nairobi",
    type: "Road",
    status: "Ongoing",
    latitude: -1.2500,
    longitude: 36.8500,
    description: "Urban road improvement project within Nairobi.",
  },
];

export default infrastructureData;